[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "volsegtools"
version = "0.0.0"
authors = [
]
description = ""
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "dask",
    "dask_image",
    "zarr",
    "numpy",
    "mrcfile",
    "nibabel",
    "pydantic",
    "typer",
    "ciftools",
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[project.scripts]
molstar-preprocessor = 'volsegtools._cli:app'

# Enable the "src" layout of the project
[tool.hatch.build.targets.wheel]
packages = ["src/volsegtools"]
