[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "volsegtools"
version = "0.1.0"
authors = [
]
description = ""
readme = "README.md"
requires-python = ">=3.9,<3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "dask",
    "dask_image",
    "zarr",
    "numpy",
    "mrcfile",
    "nibabel",
    "pydantic",
    "typer",
    "ciftools",
    "molviewspec>=1.8.1",
    "trimesh>=4.11.5",
    "tifffile>=2024.8.30",
    "h5py>=3.14.0",
    "isort>=6.1.0",
    "pyometiff>=1.0.1",
    "scikit-image>=0.24.0",
    "ome-zarr>=0.10.2",
    "sfftk-rw>=0.8.1",
    "vrmlxpy>=1.0.2",
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[project.scripts]
molstar-preprocessor = 'volsegtools._cli:app'

# Enable the "src" layout of the project
[tool.hatch.build.targets.wheel]
packages = ["src/volsegtools"]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]

[tool.bumpver]
current_version = "0.1.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "chore: Bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = "scripts/pre-bump.sh"
post_commit_hook = ""
commit = true
tag = true
push = false
allowed_branches = "master,main,default,release*"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    '^version = "{version}"',
    '^current_version = "{version}"',
]
"src/volsegtools/__init__.py" = [
    '__version__ = "{version}"',
]
